apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-local
  namespace: argocd
spec:
  project: ecommerce-local
  source:
    repoURL: 'https://github.com/ItsSoham23/ecommerce-cloud.git'
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
