AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Image Processor (resizes uploaded images)

Parameters:
  SourceBucketName:
    Type: String
    Description: Name of the S3 bucket that receives original uploads
  ProcessedBucketName:
    Type: String
    Description: Name of the S3 bucket to store processed images

Resources:
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ImageProcessorFunction
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref ProcessedBucketName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${SourceBucketName}/*
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${ProcessedBucketName}/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucketName
            Events: s3:ObjectCreated:*

Outputs:
  FunctionName:
    Description: Lambda function name
    Value: !Ref ImageProcessorFunction
