apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ecommerce
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
